runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  # SESSION_SECRET should be set in Cloud Run environment variables
  # DATABASE_URL should be set in Cloud Run environment variables if using Cloud SQL

instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1000ms
  max_pending_latency: 3000ms
  max_instances: 3

handlers:
  - url: /.*
    script: auto
    secure: always

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300